traefik:
  image: traefik:latest
  container_name: "${PROJECT_NAME}_proxy"
  ports:
    - "80:80"
    - "443:443"
  depends_on:
    - nginx
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./traefik/traefik.yml:/etc/traefik/traefik.yml
    - ./traefik/openssl:/certs
    - ./traefik/provider.yml:/etc/traefik/provider.yml
    - ./traefik/usersfile:/etc/traefik/usersfile
  labels:
    - "traefik.enable=true"
    - "traefik.http.routers.${PROJECT_NAME}_proxy.entrypoints=web"
    - "traefik.http.routers.${PROJECT_NAME}_proxy.rule=Host(`${PROXY_HOST_URI}`)"
    - "traefik.http.routers.${PROJECT_NAME}_proxy.service=api@internal"
    - "traefik.http.routers.${PROJECT_NAME}_proxy.middlewares=auth"
    - "traefik.http.services.${PROJECT_NAME}_proxy.loadBalancer.server.port=8080"
    - "traefik.http.middlewares.auth.basicauth.usersfile=/etc/traefik/usersfile"
